apiVersion: v1
kind: Service
metadata:
  name: jaeger-service
spec:
  type: ClusterIP
  ports:
    - port: 14268
      targetPort: 14268
    - port: 16686
      targetPort: 16686
    - port: 4318
      targetPort: 4318
  selector:
    app: jaeger